# Generated by Django 5.0.1 on 2024-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_forecast_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('humidity', models.FloatField()),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
